"""Select actual source fragments and reuse upstream evidence in a single reference namespace."""

import json
import re
from copy import deepcopy
from pathlib import Path
from typing import Callable
from urllib.parse import urlsplit

from langchain_core.messages import HumanMessage, SystemMessage
from openai import APITimeoutError, BadRequestError, LengthFinishReasonError

from app.config import get_settings
from app.research.evidence_context import EvidenceContext
from app.research.runtime import ResearchModelCallbacks, ResearchRuntime
from app.schemas import Claim, Evidence, Source, TaskEvidenceBundle, ResearchTask
from app.schemas.evidence_extraction import ExtractedEvidenceResult
from app.schemas.source import classify_source_url, normalize_source_url


_PROMPT = Path(__file__).resolve().parents[1] / "prompts" / "evidence_extraction.md"
MAX_EXTRACTION_INPUT_CHARS = 48000
MAX_NEW_EVIDENCE = 12


class EvidenceExtractionTimeoutError(TimeoutError):
    """An extraction request timed out after the research memo was generated."""


class EvidenceExtractionLengthError(RuntimeError):
    """Extraction remained truncated after one bounded compact-output recovery."""


class _TruncatedOutput(Exception):
    """A plain-JSON compatibility response ended with finish_reason=length."""


def extraction_output_schema(candidate_count: int, *, compact: bool = False) -> dict:
    """Constrain this request's reference choices and output size at the provider."""
    schema = deepcopy(ExtractedEvidenceResult.model_json_schema())
    valid = list(range(candidate_count))
    schema["properties"]["selected_evidence_indexes"]["items"]["enum"] = valid
    claim = schema["$defs"]["ExtractedClaim"]["properties"]
    claim["supporting_evidence_indexes"]["items"]["enum"] = valid
    claim["supporting_evidence_indexes"]["maxItems"] = 3 if compact else 4
    claim["text"]["maxLength"] = 90 if compact else 160
    schema["properties"]["claims"]["maxItems"] = 6
    if compact:
        schema["properties"]["selected_evidence_indexes"]["maxItems"] = 6
    return schema


def source_fragments(text: str) -> list[dict]:
    """Offer complete sentences and adjacent sentence groups, retaining source order.

    These are candidates, not accepted Evidence. The model selects useful fact
    units; all content is copied from actual readings, never generated by an LLM.
    Overlong units and spans equal to the whole fetched page are not offered.
    """
    text = re.sub(r"\s+", " ", text).strip()
    boundaries = [0, *(match.end() for match in re.finditer(r'(?<=[.!?。！？])\s+(?=[A-Z0-9\u4e00-\u9fff("“])', text)), len(text)]
    units = [(start, end) for start, end in zip(boundaries, boundaries[1:]) if end > start]
    fragments = []
    for position, (start, _) in enumerate(units):
        for size in (1, 2, 3):
            if position + size > len(units):
                break
            end = units[position + size - 1][1]
            while end > start and text[end - 1].isspace():
                end -= 1
            content = text[start:end]
            if 0 < len(content) <= 2000 and content != text:
                fragments.append({"content": content, "start": start, "end": end})
    return fragments


def _candidates(pages: list[dict], upstream: EvidenceContext) -> tuple[list[dict], list[dict]]:
    candidates = []
    for index, page in enumerate(pages):
        for fragment in source_fragments(page["text"]):
            candidates.append({"evidence_index": len(candidates), "origin": "fetched", "url": page["url"],
                               "title": page["title"], "content": fragment["content"],
                               "_source_index": index, "_start": fragment["start"], "_end": fragment["end"]})
    sources = {item.source_id: item for item in upstream.sources}
    upstream_indexes = {}
    for index, item in enumerate(upstream.evidence):
        source = sources[item.source_id]
        upstream_indexes[item.evidence_id] = len(candidates)
        candidates.append({"evidence_index": len(candidates), "origin": "upstream", "url": source.url,
                           "title": source.title, "content": item.content, "_upstream_index": index})
    claims = [{"task_id": item.task_id, "text": item.text,
               "supporting_evidence_indexes": [upstream_indexes[key] for key in item.evidence_ids]}
              for item in upstream.claims]
    return candidates, claims


def model_payload(payload: dict) -> dict:
    # Store repeated URL/title metadata once without changing candidate numbers
    # or dropping any source fragment. String labels cannot be confused with IDs.
    sources, labels, candidates = [], {}, []
    for item in payload["candidates"]:
        key = (item["url"], item["title"])
        if key not in labels:
            labels[key] = f"page_{len(sources)}"
            sources.append({"label": labels[key], "url": item["url"], "title": item["title"]})
        candidates.append({"evidence_index": item["evidence_index"], "origin": item["origin"],
                           "source": labels[key], "content": item["content"]})
    return {"task": payload["task"], "memo": payload["memo"], "sources": sources,
            "evidence_candidates": candidates, "upstream_claims": payload["upstream_claims"]}


def prepare_extraction_payload(task: ResearchTask, memo: str, readings: list[dict], upstream: EvidenceContext) -> dict:
    pages: dict[str, dict] = {}
    for reading in readings:
        if "error" in reading or not isinstance(reading.get("text"), str) or not reading["text"].strip():
            continue
        key = normalize_source_url(reading["url"])
        if key not in pages:
            pages[key] = {"url": reading["url"], "title": str(reading.get("title") or reading["url"])[:300],
                          "published_at": str(reading.get("published_at") or "") or None,
                          "text": re.sub(r"\s+", " ", reading["text"]).strip()[:5000]}
        elif len(reading["text"]) > len(pages[key]["text"]):
            pages[key]["text"] = re.sub(r"\s+", " ", reading["text"]).strip()[:5000]
    payload = {"task": {"task_id": task.id, "task_type": task.task_type, "question": task.question, "title": task.title},
               "memo": memo[:4000], "fetched_pages": list(pages.values())}
    while True:
        payload["candidates"], payload["upstream_claims"] = _candidates(payload["fetched_pages"], upstream)
        # Include both dynamic enums and compatibility/recovery instructions in
        # the same character budget as the source data.
        overhead = (len(_PROMPT.read_text(encoding="utf-8"))
                    + len(json.dumps(extraction_output_schema(len(payload["candidates"])), ensure_ascii=False)) + 1500)
        if len(json.dumps(model_payload(payload), ensure_ascii=False)) + overhead <= MAX_EXTRACTION_INPUT_CHARS:
            return payload
        if any(len(page["text"]) > 100 for page in payload["fetched_pages"]):
            for page in payload["fetched_pages"]:
                page["text"] = page["text"][:max(100, len(page["text"]) // 2)]
        elif len(payload["memo"]) > 100:
            payload["memo"] = payload["memo"][:max(100, len(payload["memo"]) // 2)]
        else:
            raise ValueError("Evidence extraction input exceeds its character budget.")


class EvidenceExtractor:
    def __init__(self, model):
        self.model = model
        self.prompt = _PROMPT.read_text(encoding="utf-8")

    def extract(self, payload: dict, runtime: ResearchRuntime) -> ExtractedEvidenceResult:
        runtime.remaining()
        if not payload["candidates"]:
            runtime.log("evidence extraction skipped: no source fragment candidates")
            return ExtractedEvidenceResult()
        data_message = HumanMessage(content=json.dumps(model_payload(payload), ensure_ascii=False, separators=(",", ":")))
        config = {"callbacks": [ResearchModelCallbacks(runtime)]}
        settings = get_settings()

        def invoke(model, request, max_tokens):
            # Override this request only: the shared research model retains its
            # normal timeout. Even the compatibility call uses remaining time.
            timeout = min(settings.evidence_extraction_timeout_seconds, runtime.remaining())
            runtime.log(
                f"evidence extraction request: input_chars={sum(len(message.text) for message in request)} "
                f"candidates={len(payload['candidates'])} timeout={timeout:.2f}s "
                f"max_tokens={max_tokens}"
            )
            options = {"timeout": timeout}
            host = urlsplit(str(getattr(self.model, "openai_api_base", "") or "")).hostname
            if host in {"api.siliconflow.cn", "api.siliconflow.com"}:
                # LangChain renames max_tokens to max_completion_tokens.
                # SiliconFlow documents max_tokens, so send its actual field
                # via extra_body while preserving any existing provider options.
                options["extra_body"] = {**(getattr(self.model, "extra_body", None) or {}),
                                         "max_tokens": max_tokens}
            else:
                options["max_tokens"] = max_tokens
            model_name = str(getattr(self.model, "model_name", ""))
            if host and host.endswith(".aliyuncs.com") and model_name.startswith("qwen3.7-"):
                # Override extraction only; the shared research model keeps its
                # original thinking configuration and request timeout.
                options["extra_body"] = {**(getattr(self.model, "extra_body", None) or {}),
                                         "enable_thinking": settings.evidence_extraction_enable_thinking}
            try:
                result = model.invoke(request, config=config, **options)
            except APITimeoutError as error:
                raise EvidenceExtractionTimeoutError(
                    f"Evidence extraction model request timed out for task {runtime.task_id} "
                    f"(request timeout={timeout:.2f}s). The research memo was generated, "
                    "but its evidence bundle was not published. "
                    "Check model service latency or EVIDENCE_EXTRACTION_TIMEOUT_SECONDS."
                ) from error
            runtime.remaining()
            return result

        use_native = True

        def extract_once(*, compact=False):
            nonlocal use_native
            schema = extraction_output_schema(len(payload["candidates"]), compact=compact)
            instructions = ("\nCURRENT OUTPUT LIMITS: at most 6 claims, each <=90 characters, each <=3 references; "
                            "at most 6 standalone selections. Return one short complete JSON object."
                            if compact else
                            "\nCURRENT OUTPUT LIMITS: at most 6 claims, each <=160 characters, each <=4 references.")
            prompt = self.prompt + instructions
            max_tokens = (min(8192, max(1024, settings.evidence_extraction_max_tokens * 2))
                          if compact else settings.evidence_extraction_max_tokens)
            if use_native:
                try:
                    structured = self.model.with_structured_output(schema, method="json_schema")
                    return invoke(structured, [SystemMessage(content=prompt), data_message], max_tokens)
                except (NotImplementedError, TypeError, BadRequestError) as error:
                    if isinstance(error, BadRequestError) and not any(
                        term in str(error).lower() for term in ("json_schema", "response_format")
                    ):
                        raise
                    runtime.remaining()
                    use_native = False
                    runtime.log("native evidence JSON Schema unavailable; using schema-validated JSON")
            fallback = [SystemMessage(content=prompt + "\nReturn only JSON matching this schema:\n"
                                      + json.dumps(schema, ensure_ascii=False)), data_message]
            response = invoke(self.model, fallback, max_tokens)
            if response.response_metadata.get("finish_reason") == "length":
                raise _TruncatedOutput()
            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
            return json.loads(raw)

        try:
            result = extract_once()
        except (LengthFinishReasonError, _TruncatedOutput):
            runtime.remaining()
            runtime.log("evidence output truncated; compact recovery 1/1 (same sources, no new research)")
            try:
                result = extract_once(compact=True)
            except (LengthFinishReasonError, _TruncatedOutput) as error:
                raise EvidenceExtractionLengthError(
                    f"Evidence extraction output remained truncated for task {runtime.task_id} after one compact recovery attempt. "
                    "No incomplete JSON or evidence bundle was published."
                ) from error
        return filter_candidate_references(ExtractedEvidenceResult.model_validate(result), payload, runtime.log)


def filter_candidate_references(extracted: ExtractedEvidenceResult, payload: dict,
                                report: Callable[[str], None] | None = None) -> ExtractedEvidenceResult:
    """Omit an entire claim with an unknown reference; preserve other complete chains."""
    count = len(payload["candidates"])
    standalone = [index for index in extracted.selected_evidence_indexes if index < count]
    claims = [claim for claim in extracted.claims if all(index < count for index in claim.supporting_evidence_indexes)]
    invalid = set(index for index in extracted.selected_evidence_indexes if index >= count)
    invalid.update(index for claim in extracted.claims for index in claim.supporting_evidence_indexes if index >= count)
    if invalid and report:
        report(f"evidence references filtered: candidate_count={count} invalid_indexes={sorted(invalid)} "
               f"claims_omitted={len(extracted.claims) - len(claims)} "
               f"standalone_omitted={len(extracted.selected_evidence_indexes) - len(standalone)}")
    return ExtractedEvidenceResult(selected_evidence_indexes=standalone, claims=claims)


def limit_evidence_selection(extracted: ExtractedEvidenceResult, payload: dict,
                             report: Callable[[str], None] | None = None) -> ExtractedEvidenceResult:
    """Keep complete claim support sets within the task's new-evidence budget.

    Model output order determines claim priority. Upstream references consume no
    new-evidence capacity. Optional standalone selections use the remaining slots.
    Never remove one reference from a retained claim to make it fit.
    """
    selected = set(extracted.selected_evidence_indexes)
    selected.update(index for claim in extracted.claims for index in claim.supporting_evidence_indexes)
    if any(index >= len(payload["candidates"]) for index in selected):
        raise ValueError("Extraction references an unknown Evidence candidate index.")
    # Validate all requested fetched fragments before any capacity filtering, so
    # overflow cannot hide an invented excerpt or an invalid reference.
    for index in selected:
        candidate = payload["candidates"][index]
        if candidate["origin"] == "fetched":
            page = payload["fetched_pages"][candidate["_source_index"]]
            content = page["text"][candidate["_start"]:candidate["_end"]]
            if content != candidate["content"] or content == page["text"]:
                raise ValueError("Evidence candidate does not match an original source fragment.")

    def fresh(indexes):
        return {index for index in indexes if payload["candidates"][index]["origin"] == "fetched"}

    new_indexes, claims = set(), []
    for claim in extracted.claims:
        required = fresh(claim.supporting_evidence_indexes)
        if len(new_indexes | required) <= MAX_NEW_EVIDENCE:
            claims.append(claim)
            new_indexes.update(required)
    standalone = []
    for index in extracted.selected_evidence_indexes:
        required = fresh([index])
        if len(new_indexes | required) <= MAX_NEW_EVIDENCE:
            standalone.append(index)
            new_indexes.update(required)
    limited = ExtractedEvidenceResult(selected_evidence_indexes=standalone, claims=claims)
    kept = set(standalone)
    kept.update(index for claim in claims for index in claim.supporting_evidence_indexes)
    if report and (len(claims) != len(extracted.claims) or kept != selected):
        report(f"evidence selection limited: new_evidence={len(new_indexes)}/{MAX_NEW_EVIDENCE} "
               f"claims_kept={len(claims)} claims_omitted={len(extracted.claims) - len(claims)} "
               f"candidates_omitted={len(selected - kept)}")
    return limited


def build_evidence_bundle(task: ResearchTask, extracted: ExtractedEvidenceResult, payload: dict, upstream: EvidenceContext,
                          *, report: Callable[[str], None] | None = None) -> TaskEvidenceBundle:
    """Check reference provenance, copy original text, and assign program-generated IDs."""
    extracted = ExtractedEvidenceResult.model_validate(extracted.model_dump())
    extracted = filter_candidate_references(extracted, payload, report)
    extracted = limit_evidence_selection(extracted, payload, report)
    selected = set(extracted.selected_evidence_indexes)
    selected.update(index for claim in extracted.claims for index in claim.supporting_evidence_indexes)
    if any(index >= len(payload["candidates"]) for index in selected):
        raise ValueError("Extraction references an unknown Evidence candidate index.")
    sources: dict[int, Source] = {}
    evidence: list[Evidence] = []
    evidence_ids: dict[int, str] = {}
    for index in sorted(selected):
        candidate = payload["candidates"][index]
        if candidate["origin"] == "upstream":
            evidence_ids[index] = upstream.evidence[candidate["_upstream_index"]].evidence_id
            continue
        if len(evidence) >= MAX_NEW_EVIDENCE:
            raise ValueError("Evidence selection did not enforce the new-evidence budget.")
        source_index = candidate["_source_index"]
        page = payload["fetched_pages"][source_index]
        content = page["text"][candidate["_start"]:candidate["_end"]]
        if content != candidate["content"] or content == page["text"]:
            raise ValueError("Evidence candidate does not match an original source fragment.")
        if source_index not in sources:
            kind = classify_source_url(page["url"])
            sources[source_index] = Source(task_id=task.id, url=page["url"], title=page["title"], source_type=kind,
                                           published_at=page.get("published_at"))
        item = Evidence(task_id=task.id, source_id=sources[source_index].source_id, content=content,
                        location=f"normalized-text chars {candidate['_start']}:{candidate['_end']}")
        evidence.append(item)
        evidence_ids[index] = item.evidence_id
    claims = [Claim(task_id=task.id, text=item.text, evidence_ids=[evidence_ids[index] for index in item.supporting_evidence_indexes])
              for item in extracted.claims]
    return TaskEvidenceBundle(task_id=task.id, sources=list(sources.values()), evidence=evidence, claims=claims)
